-- V1__init.sql: tablas iniciales users, courts, bookings

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS users (
  id_user BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name_user VARCHAR(100) NOT NULL,
  photo_url VARCHAR(255),
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  points INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS courts (
  id_court BIGINT AUTO_INCREMENT PRIMARY KEY,
  id_owner BIGINT NOT NULL,
  name_court VARCHAR(100) NOT NULL,
  direction VARCHAR(255) NOT NULL,
  lat DOUBLE NULL,
  lng DOUBLE NULL,
  price DECIMAL(10,2) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_court_owner FOREIGN KEY (id_owner) REFERENCES users(id_user) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
  id_booking BIGINT AUTO_INCREMENT PRIMARY KEY,
  id_court BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_booking_court FOREIGN KEY (id_court) REFERENCES courts(id_court) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_booking_user FOREIGN KEY (created_by) REFERENCES users(id_user) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX idx_booking_start (start_time),
  INDEX idx_booking_court (id_court)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
